// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiVAH8N_K47CHQ9PU_P-9oPgKdlHEi7mc',
    appId: '1:890513393912:web:ceab69f88516a038f2130d',
    messagingSenderId: '890513393912',
    projectId: 'elitestaff-51f88',
    authDomain: 'elitestaff-51f88.firebaseapp.com',
    storageBucket: 'elitestaff-51f88.firebasestorage.app',
    measurementId: 'G-Q24D5SK37P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIHElWdE5qMRbSDfIWqo2fZ4QUKvPuSoY',
    appId: '1:890513393912:android:fb407d87bc11a7fef2130d',
    messagingSenderId: '890513393912',
    projectId: 'elitestaff-51f88',
    storageBucket: 'elitestaff-51f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmgZnBtEdGv7956ZPkzN32Jl_tejyj7c8',
    appId: '1:890513393912:ios:7e7fb5cfa14cbb26f2130d',
    messagingSenderId: '890513393912',
    projectId: 'elitestaff-51f88',
    storageBucket: 'elitestaff-51f88.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmgZnBtEdGv7956ZPkzN32Jl_tejyj7c8',
    appId: '1:890513393912:ios:7e7fb5cfa14cbb26f2130d',
    messagingSenderId: '890513393912',
    projectId: 'elitestaff-51f88',
    storageBucket: 'elitestaff-51f88.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiVAH8N_K47CHQ9PU_P-9oPgKdlHEi7mc',
    appId: '1:890513393912:web:15b2d1259db87babf2130d',
    messagingSenderId: '890513393912',
    projectId: 'elitestaff-51f88',
    authDomain: 'elitestaff-51f88.firebaseapp.com',
    storageBucket: 'elitestaff-51f88.firebasestorage.app',
    measurementId: 'G-SJSBK9M5P7',
  );
}
